### ISSUE TITLE
Support dependencies autoupdate 🆙️

### ISSUE THREAD

**Issue by imanushin** [Citi/gradle-helm-plugin#23]
Support a way of automatic dependency updates (add some bot?).

**Comment by JamieSlome** [comment]
The following should enable Dependabot:

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

You'll need to find the right value for `package-ecosystem` and make sure the `directory` points to where your package manifest sits.
